env: development
jwt:
  secret: 23123
  expiresIn: 30d
db:
  mysql:
    url: localhost
    port: 3306
    username: root
    password:
    database: nest-course
file:
  upload:
    dir: C:/Users/Administrator/Downloads
